<?php

$color[] = "aliceblue";
$color[] = "antiquewhite";
$color[] = "aqua";
$color[] = "aquamarine";
$color[] = "azure";
$color[] = "beige";
$color[] = "bisque";
$color[] = "black";
$color[] = "blanchedalmond";
$color[] = "blue";
$color[] = "blueviolet";
$color[] = "brown";
$color[] = "burlywood";
$color[] = "cadetblue";
$color[] = "chartreuse";
$color[] = "chocolate";
$color[] = "coral";
$color[] = "cornflowerblue";
$color[] = "cornsilk";
$color[] = "crimson";
$color[] = "cyan";
$color[] = "darkblue";
$color[] = "darkcyan";
$color[] = "darkgoldenrod";
$color[] = "darkgray";
$color[] = "darkgreen";
$color[] = "darkkhaki";
$color[] = "darkmagenta";
$color[] = "darkolivegreen";
$color[] = "darkorange";
$color[] = "darkorchid";
$color[] = "darkred";
$color[] = "darksalmon";
$color[] = "darkseagreen";
$color[] = "darkslateblue";
$color[] = "darkslategray";
$color[] = "darkturquoise";
$color[] = "darkviolet";
$color[] = "deeppink";
$color[] = "deepskyblue";
$color[] = "dimgray";
$color[] = "dodgerblue";
$color[] = "firebrick";
$color[] = "floralwhite";
$color[] = "forestgreen";
$color[] = "fuchsia";
$color[] = "gainsboro";
$color[] = "ghostwhite";
$color[] = "gold";
$color[] = "goldenrod";
$color[] = "gray";
$color[] = "green";
$color[] = "greenyellow";
$color[] = "honeydew";
$color[] = "hotpink";
$color[] = "indianred";
$color[] = "indigo";
$color[] = "ivory";
$color[] = "khaki";
$color[] = "lavender";
$color[] = "lavenderblush";
$color[] = "lawngreen";
$color[] = "lemonchiffon";
$color[] = "lightblue";
$color[] = "lightcoral";
$color[] = "lightcyan";
$color[] = "lightgoldenrodyellow";
$color[] = "lightgreen";
$color[] = "lightgrey";
$color[] = "lightpink";
$color[] = "lightsalmon";
$color[] = "lightseagreen";
$color[] = "lightskyblue";
$color[] = "lightslategray";
$color[] = "lightsteelblue";
$color[] = "lightyellow";
$color[] = "lime";
$color[] = "limegreen";
$color[] = "linen";
$color[] = "magenta";
$color[] = "maroon";
$color[] = "mediumaquamarine";
$color[] = "mediumblue";
$color[] = "mediumorchid";
$color[] = "mediumpurple";
$color[] = "mediumseagreen";
$color[] = "mediumslateblue";
$color[] = "mediumspringgreen";
$color[] = "mediumturquoise";
$color[] = "mediumvioletred";
$color[] = "midnightblue";
$color[] = "mintcream";
$color[] = "mistyrose";
$color[] = "moccasin";
$color[] = "navajowhite";
$color[] = "navy";
$color[] = "navyblue";
$color[] = "oldlace";
$color[] = "olive";
$color[] = "olivedrab";
$color[] = "orange";
$color[] = "orangered";
$color[] = "orchid";
$color[] = "palegoldenrod";
$color[] = "palegreen";
$color[] = "paleturquoise";
$color[] = "palevioletred";
$color[] = "papayawhip";
$color[] = "peachpuff";
$color[] = "peru";
$color[] = "pink";
$color[] = "plum";
$color[] = "powderblue";
$color[] = "purple";
$color[] = "red";
$color[] = "rosybrown";
$color[] = "royalblue";
$color[] = "saddlebrown";
$color[] = "salmon";
$color[] = "sandybrown";
$color[] = "seagreen";
$color[] = "seashell";
$color[] = "sienna";
$color[] = "silver";
$color[] = "skyblue";
$color[] = "slateblue";
$color[] = "slategray";
$color[] = "snow";
$color[] = "springgreen";
$color[] = "steelblue";
$color[] = "tan";
$color[] = "teal";
$color[] = "thistle";
$color[] = "tomato";
$color[] = "turquoise";
$color[] = "violet";
$color[] = "wheat";
$color[] = "white";
$color[] = "whitesmoke";
$color[] = "yellow";
$color[] = "yellowgreen ";

$color2 = $color;

foreach ($color as $c) {
  foreach ($color2 as $c2) {
    if($c != $c2) {
      echo ".".trim($c)."_".trim($c2)." {\n";
      echo "background-color: ".trim($c).";\n";
      echo "animation-name: ".trim($c)."_".trim($c2).";\n";
      echo "animation-duration: var(--color-animation-duration);\n";
      echo "animation-iteration-count: infinite;\n";
      echo "animation-direction: alternate;\n";
      echo "}\n";

      echo "@keyframes ".trim($c)."_".trim($c2)." {\n";
      echo "from {background-color: ".trim($c).";}\n";
      echo "to {background-color: ".trim($c2).";}\n";
      echo "}\n";
    }
  }
}

?>